In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
y = x
y_copy = np.copy(x)

In [ ]:
y

array([1, 2, 3])

In [ ]:
x[0]  = -2  # teraz dokonam zmiany w zmiennej y

In [ ]:
y

array([-2,  2,  3])

In [ ]:
x

array([-2,  2,  3])

In [ ]:
id(x), id(y)

(136176669393520, 136176669393520)

In [ ]:
y_copy

array([1, 2, 3])

In [ ]:
y_copy[0] = -3

In [ ]:
x, y

(array([-2,  2,  3]), array([-2,  2,  3]))

In [ ]:
y_copy

array([-3,  2,  3])

In [ ]:
id(y_copy)

136176669323984

In [ ]:
import pandas as pd

In [ ]:
series_original = pd.Series([1,2,3])

In [ ]:
series_copy = pd.Series(deepcopy(series_original.to_dict()))